// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC14JC3SGUnukVpDYwQCzeeUfge7e-vk0',
    appId: '1:1020106177580:web:d9363e2ddea811d3bea589',
    messagingSenderId: '1020106177580',
    projectId: 'crudfirebase-2b061',
    authDomain: 'crudfirebase-2b061.firebaseapp.com',
    storageBucket: 'crudfirebase-2b061.appspot.com',
    measurementId: 'G-0ZZ0HRM1L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwbSL5WbnjCdQrrCy0CYiQ3bpB8YgvWM',
    appId: '1:1020106177580:android:97528657989d0258bea589',
    messagingSenderId: '1020106177580',
    projectId: 'crudfirebase-2b061',
    storageBucket: 'crudfirebase-2b061.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGK2i6gC9DGuuNBmzZaiqlj-CP8Lc2vfg',
    appId: '1:1020106177580:ios:384028351d3f9a71bea589',
    messagingSenderId: '1020106177580',
    projectId: 'crudfirebase-2b061',
    storageBucket: 'crudfirebase-2b061.appspot.com',
    iosClientId: '1020106177580-56vrinsv3mc6lcafobge3jqlg20vjb2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGK2i6gC9DGuuNBmzZaiqlj-CP8Lc2vfg',
    appId: '1:1020106177580:ios:6c5f92a122acb4ffbea589',
    messagingSenderId: '1020106177580',
    projectId: 'crudfirebase-2b061',
    storageBucket: 'crudfirebase-2b061.appspot.com',
    iosClientId: '1020106177580-ovi4a74n2q3sk13d0p2hpagkj031tasf.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase.RunnerTests',
  );
}
